### ISSUE TITLE
Use pace-util rather than fv3gfs-util?

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3gfs-wrapper#298]
@mcgibbon Should we update the dependency to use the new home of fv3gfs-util? This prevents fv3net from using pace-util.

https://github.com/ai2cm/fv3gfs-wrapper/blob/5e9dc78117ad470ef84bff51689333b4ecf0fca7/setup.py#L60

**Comment by mcgibbon** [comment]
I think that makes sense. We can also have it use the version on pypi.

**Comment by nbren12** [comment]
I think it's a reasonably high priority so that fv3net doesn't get stuck on a non-maintained pypi package. Also refactoring any fv3gfs.util imports in fv3net.

**Comment by mcgibbon** [comment]
Fixed by https://github.com/ai2cm/fv3gfs-wrapper/pull/299
